services:
  - type: web
    name: research-assistant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SERPER_API_KEY
        sync: false
      - key: BRAVE_API_KEY
        sync: false
